#!/bin/bash
#
set -e

. /usr/share/debconf/confmodule

chown -R docintel:docintel /usr/lib/docintel/document-indexer/

cp /usr/share/doc/docintel/nlog.config.worker-example /usr/lib/docintel/document-indexer/nlog.config
sed -i "s,WORKER_NAME,document-indexer,g" /usr/lib/docintel/document-indexer/nlog.config

exit 0


