#!/bin/bash
#
set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.pgsql

dbc_pgsql_createdb_encoding="UTF8"
dbc_generate_include="template:/etc/docintel/appsettings.json"
dbc_generate_include_args="-o template_infile=/usr/share/doc/docintel/appsettings.json.example"
dbc_generate_include_owner="docintel"
dbc_generate_include_perms=0640

dbc_go docintel-core $@

if [ -f "/usr/share/doc/docintel/nlog.config.example" ]; then
    cp /usr/share/doc/docintel/nlog.config.example /etc/docintel/nlog.config
fi

# when upgrading a packet, it is called as postinst configure X.X.X where X.X.X is the previous version
# when installing a packet (from scratch) there is no parameter 
if [ -z "$2" ]
then
    su - solr -c "/opt/solr/bin/solr create -c tag || true"
    su - solr -c "/opt/solr/bin/solr create -c document || true"
    su - solr -c "/opt/solr/bin/solr create -c source || true"
    su - solr -c "/opt/solr/bin/solr create -c facet || true"

    if [ -d "/var/solr/data/tag/conf/" ]; then
        cp /usr/share/docintel/managed-schema-tag /var/solr/data/tag/conf/managed-schema
        chown solr:solr /var/solr/data/tag/conf/managed-schema
    fi

    if [ -d "/var/solr/data/document/conf/" ]; then
        cp /usr/share/docintel/managed-schema-document /var/solr/data/document/conf/managed-schema
        cp /usr/share/docintel/solrconfig-document.xml /var/solr/data/document/conf/solrconfig.xml
        chown solr:solr /var/solr/data/document/conf/managed-schema
        chown solr:solr /var/solr/data/document/conf/solrconfig.xml
    fi

    if [ -d "/var/solr/data/source/conf/" ]; then
        cp /usr/share/docintel/managed-schema-source /var/solr/data/source/conf/managed-schema
        chown solr:solr /var/solr/data/source/conf/managed-schema
    fi

    if [ -d "/var/solr/data/facet/conf/" ]; then
        cp /usr/share/docintel/managed-schema.xml /var/solr/data/facet/conf/managed-schema
        chown solr:solr /var/solr/data/facet/conf/managed-schema
    fi

    systemctl stop solr
    systemctl start solr
fi

chown -R docintel:docintel /etc/docintel/

exit 0


