#!/bin/bash
#
set -e

SOLR_BIN="${SOLR_FOLDER:-/opt/solr}/bin"
echo "Using ${SOLR_BIN} for SolR binaries"
SOLR_DATA="${SOLR_DATA_FOLDER:-/var/solr/data}"
echo "Using ${SOLR_DATA} for SolR data"

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql ]; then
	. /usr/share/dbconfig-common/dpkg/postrm.pgsql
	dbc_go docintel-core $@
fi

case "$1" in
  remove)
    su - solr -c "$SOLR_BIN/solr delete -c tag || true"
    su - solr -c "$SOLR_BIN/solr delete -c document || true"
    su - solr -c "$SOLR_BIN/solr delete -c source || true"
    su - solr -c "$SOLR_BIN/solr delete -c facet || true"
    curl -XDELETE localhost:9200/observables || true
    curl -XDELETE localhost:9200/relationship || true
    curl -XDELETE localhost:9200/whitelist || true
    ;;
  purge)
    rm -rf /etc/docintel
    ;;
  
esac

exit 0

