#!/bin/bash
#
set -e

service_exists() {
    local n=$1
    if [[ $(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ') == $n.service ]]; then
        return 0
    else
        return 1
    fi
}


if ! id "docintel" &>/dev/null; then
    /usr/sbin/groupadd -r docintel 2>/dev/null
    /usr/sbin/useradd -g docintel -s /sbin/nologin -r docintel --home /usr/lib/docintel 2>/dev/null
fi

echo "Checking for dependencies"

if ! service_exists solr; then
    echo "Solr is not installed."
    exit 1
fi

mkdir -p /etc/docintel/

mkdir -p /data/docintel/
chown -R docintel:docintel /data/docintel/

mkdir -p /var/log/docintel/
chown -R docintel:docintel /var/log/docintel/

exit 0


